### ISSUE TITLE
File Redirect Support

### ISSUE THREAD

**Issue by jamietotten** [silverstripe/silverstripe-redirectedurls#21]
I'm wondering of this will ever support asset folder file redirection or if that's just opening a huge amount problems. Is that possible?

**Comment by michalkleiner** [comment]
If we added https://github.com/sheadawson/silverstripe-linkable for the destination, it would support File, SiteTree page and other types out of the box. That would solve #37 as well.

I believe it could be married together without breaking BC while slightly limiting the amount of options Linkable offers (e.g. removing the email option).

**Comment by dhensby** [comment]
Does it not currently work if the asset is missing? Any URLs that point to missing assets should be passed to the framework

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
