### ISSUE TITLE
Addition of "Domain" field to RedirectedURL model

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-redirectedurls#28]
It would very helpful to have the ability to show and to sort-by "Domain" when viewing pages and pages of redirections in the module's GridField.

Some projects I have worked-on that rely on this (Great but woefully underrated) module, have upwards of 10 legacy domains for which redirects need to be implemented. The ability to sort and view by domain would be very useful.

**Comment by michalkleiner** [comment]
@phptek do you mean a domain field for the 'To' URL?

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
