### ISSUE TITLE
Causes errors with array GET vars

### ISSUE THREAD

**Issue by jameshoward** [silverstripe/silverstripe-redirectedurls#32]
E.g. a URL with ?type[0]=large causes:

`Warning at redirectedurls/code/RedirectedURLHandler.php line 25: strtolower() expects parameter 1 to be string, array given`

Caused by `arrayToLowercase` assuming all values in the request vars will be strings.

**Comment by nfauchelle** [comment]
This was fixed in 0b30c9257d0d0551aba7cf2885bd4b6469bffdb1 and 9ce9475d275ad650ad61a8dfeeca75d4ac18d4fa
:-)
