### ISSUE TITLE
Redirect to a certain Page (enhancement)

### ISSUE THREAD

**Issue by Taitava** [silverstripe/silverstripe-redirectedurls#37]
In addition of writing the `To` field manually, there could be an alternative way to select the destination from a dropdown list. One benefit of this would be just convenience, but the main point is to ensure that the redirection works in the future too, if the target `Page` gets relocated under a different page or if its `URLSegment` field gets changed

What do you think? :)

Of course it's still needed to provide a way to input the target URL manually if the user wants to, so I don't propose to change that in any way. Perhaps I can create this feature also myself, but as this is not a mandatory feature for my use case, I will just leave it for now and perhaps start working on it later.

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.
