### ISSUE TITLE
'From' URI at top level doesn't seem to work

### ISSUE THREAD

**Issue by stevevu** [silverstripe/silverstripe-redirectedurls#42]
Hi,

The following "From" URI doesn't appear to work:

/product_compliance_definitions.html

Requesting this page results in a 404 error.  I also tried /legacy-page.html w/o success.

However, if I make it second level page, eg:

/about/product_compliance_definitions.html

, the redirect will work.  

I've confirmed that the 'To' URI (/quality) does exist on the site.

Please advise.

thanks!
Steve

**Comment by stevevu** [comment]
bump

**Comment by dhensby** [comment]
I've added a test in PR #45 to try to replicate this.

**Comment by dhensby** [comment]
I've tested locally (SilverStripe 3.x-dev and v1.0.1 of RedirectedURLs) and I can't replicate this problem.

My test passes too. Please can you provide a failing test to show this problem?

**Comment by dhensby** [comment]
closing, can't replicate and no response from initial reporter
