### ISSUE TITLE
Compatibility for SilverStripe 3.7 and PHP 7 requirements

### ISSUE THREAD

**Issue by sinan-evanshunt** [silverstripe/silverstripe-redirectedurls#62]
SilverStripe switched from using Object to SS_Object in order to avoid conflict with PHP 7 name space of Object.

See https://docs.silverstripe.org/en/3/changelogs/3.7.0

in `_config.php` all usage of `Object::add_extension` should be replaced by `SS_Object::add_extension`

**Comment by wilr** [comment]
Fixed in ae1a042fa085c33f92e4a20b1f3e72b905ab6ab9
