### ISSUE TITLE
URLs starting with '/assets' are ignored

### ISSUE THREAD

**Issue by oddnoc** [silverstripe/silverstripe-redirectedurls#82]
If you create a redirect referencing the /assets path, you get a 404 rather than a redirect. I've confirmed this on both Apache and Nginx.

**Comment by thats4shaw** [comment]
Confirmed here too.

**Comment by dhensby** [comment]
fixed by #80 I presume

**Comment by satrun77** [comment]
Fixed by https://github.com/silverstripe/silverstripe-redirectedurls/pull/86
